apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ioqtdjm2n-go 
  janus-idp.io/tekton: ioqtdjm2n-go
  backstage.io/kubernetes-id: ioqtdjm2n-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ioqtdjm2n-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml